<p style="text-align:center"><strong><u>Privacy Policy </u></strong></p>

<p>&nbsp;</p>

<p>This privacy policy constitutes an integral part of the terms and conditions of use of the AKDN MER Consultant Database (the &ldquo;Consultant Database&rdquo;), which is owned and operated by the Aga Khan Foundation (the &ldquo;Foundation&rdquo;). It describes the ways that the Foundation undertakes to protect your personal data (and that of the person or persons for whom you act as legal representative) (the &ldquo;Personal Data&rdquo;), the way in which we collect information from you when you use the Consultant Database and for what such data may be used. This privacy policy applies to any information obtained by the Foundation through your use of the Consultant Database. It is not applicable to any internet websites controlled by third parties that the Consultant Database may link to (&ldquo;Third Party Sites&rdquo;). Please review the privacy statements of Third Party Sites, as the Foundation is not responsible for and has no influence on the content or the privacy practices of Third Party Sites.</p>

<p>1.&nbsp;&nbsp;&nbsp; Personal Data is collected from you in various ways.</p>

<p>From time to time, there may be projects, programmes and services which may allow you to provide Personal Data to us via the Consultant Database. By providing Personal Data, you are consenting to the Foundation&rsquo;s use of the Personal Data, and you consent that the Foundation may disclose this information to other members of the AKDN and related entities or to third party providers, inside or outside your country of residence, for data processing. You also consent to the retention of this Personal Data.</p>

<p>In particular, your Personal Data can be collected as set out in the Appendix to this privacy policy.</p>

<p>You are entitled to a copy of your Personal Data and to have it rectified or deleted as required by applicable data protection legislation. <strong>Should you have any concerns or requests regarding your Personal Data, you may send an e-mail to </strong><a href="mailto:data.protection@akdn.org"><strong>data.protection@akdn.org</strong></a><strong>.</strong> Please note it may take some time to process your request and to cancel your participation, if this is requested. During any such period your Personal Data will still be available on the Consultant Database. We will endeavour to amend or remove your information from the Consultant Database as quickly as is reasonably possible.</p>

<p>2.&nbsp;&nbsp;&nbsp; No one under age is allowed to enter any Personal Data or otherwise communicate with the Consultant Database, unless the legal representative or representatives of the minor (generally the minor&#39;s parents or parent) and us expressly consent in advance. Personal Data entered by a minor unbeknownst to us without such consent will be deleted from our database as quickly as possible after we become aware of the fact.</p>

<p>3. We use appropriate technical and organisational security measures in order to protect Personal Data against unauthorised access, accidental or intentional manipulation, loss and destruction.</p>

<p>4. In order to administer the Consultant Database, we may need to transfer Personal Data to locations outside the European Economic Area (the &ldquo;EEA&rdquo;) and process Personal Data in locations outside the EEA. The level of data protection offered in such jurisdictions may be less than that offered within the EEA. By clicking &ldquo;subscribe&rdquo;, &ldquo;submit&rdquo; &ldquo;log in&rdquo;, or &ldquo;submit by e-mail&rdquo;, as the case may be, or any other such term which results in you sending us Personal Data, you accept this privacy policy and you provide express consent to such transfers.</p>

<p>5.<strong>&nbsp;&nbsp;&nbsp; </strong>The Foundation may disclose Personal Data when required by law or regulation or in the good faith belief that such action is necessary in order to conform to applicable law, comply with legal mandates, or to protect the rights, property, or personal safety of personnel of the Foundation, other members of the AKDN, related entities, the Consultant Database&rsquo;s users or the public.</p>

<p>6.&nbsp;&nbsp;&nbsp; The Consultant Database uses &ldquo;cookies&rdquo; (text files) which will be saved on your computer and which will allow an analysis of your use of the Consultant Database. This information will be used to compile reports about the Consultant Database activities for the Consultant Database operator and will facilitate provision of additional services in relation to the Consultant Database and internet utilization. If you do not wish to receive &ldquo;cookies&rdquo;, you may set your web browser to reject these, if your browser so permits.</p>

<p>7.&nbsp;&nbsp;&nbsp; The Consultant Database keeps track of user activity via log files stored on our web servers. The log files include information on IP addresses, browser types and versions, pages viewed, and entry and exit paths. Log files assist us in offering a personalised Web experience, diagnosing server problems, administering the website and tailoring information for the end-user.</p>

<p>8.&nbsp;&nbsp;&nbsp; The Consultant Database uses Google Analytics, a web analytics service provided by Google, Inc. (&ldquo;Google&rdquo;). Google Analytics uses cookies to help the Consultant Database analyse how users use the Consultant Database. The information generated by the cookie about your use of the Consultant Database (including your IP address) may be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the Consultant Database, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google&#39;s behalf. Google will not associate your IP address with any other data held by Google. By using the Consultant Database, you consent to the processing of data about you by Google in the manner and for the purposes set out above.</p>

<p>9.&nbsp;&nbsp;&nbsp; If you have consented to receiving e-mail from us, we may include a Web beacon in such e-mails to allow us to determine the number of people who open our emails and the links on which they click. Web beacons can be refused when delivered via email. If you do not wish to receive Web beacons via email, you will need to disable HTML images in your email software.</p>

<p>10.&nbsp; By using the Consultant Database, you acknowledge that you have read the terms of this privacy policy and that you consent to our use of data for the purposes set out above. This privacy policy may be amended from time to time and any changes will be posted on the Consultant Database and will become effective when posted.</p>

<p>11.&nbsp; Should you have any concerns or requests regarding your Personal Data, please send an e-mail to <a href="mailto:data.protection@akdn.org">data.protection@akdn.org</a> or contact the Foundation at: Aga Khan Foundation, 1 &ndash; 3 Avenue de la Paix, 1211 Geneva, Switzerland.</p>

<p>&nbsp;</p>

<p><strong>APPENDIX</strong></p>

<p>You are registering as a consultant with the AKDN MER Consultant Database, maintained by the AKDN Quality of Life Monitoring, Evaluation and Research Support Unit of the Foundation. By providing all the relevant personal information regarding contact(s), language(s), skills and competencies, you are providing your Personal Data to us via the Consultant Database. Through &ldquo;upload resume&rdquo; and/or &ldquo;LinkedIn URL&rdquo; and/or &ldquo;Personal website/blog&rdquo;, you acknowledge and agree that the Foundation and other members of the AKDN and related entities may review the available information on you and may access other third party profile data in order to assess your suitability for a consultancy mandate. By ticking the check-box next to the words &ldquo;I agree to the Terms and Conditions&rdquo;, you will be agreeing to the terms and conditions, the privacy policy and the possible transfer of your Personal Data to other countries. By clicking &ldquo;Register&rdquo;, verifying your registration and &ldquo;Login&rdquo;, you will maintain a consultant profile which you can update at will. By clicking &ldquo;Edit Profile&rdquo; and/or &ldquo;Update&rdquo; within your profile, you will be able to modify your profile data and submit modified or additional Personal Data to us. Additionally, you consent that the Foundation may disclose to other members of the AKDN and related entities, inside or outside your country of residence, the information contained in your consultant profile, to determine if there is a potential match with a consultancy mandate. You also consent to the Foundation, other members of the AKDN and related entities retaining your Personal Data in order to be considered for potential consultancy mandates arising in the future.</p>